---
- name: WAIT FOR SSH TO BE AVAILABLE
  hosts: all
  gather_facts: false
  tasks:
    - name: ENSURE SSH PORT OPEN
      ansible.builtin.wait_for:
        host: "{{ (ansible_ssh_host | default(ansible_host)) | default(inventory_hostname) }}"
        port: 22
        state: started
        timeout: 300
        delay: 10
        search_regex: OpenSSH
      vars:
        ansible_connection: local
        ansible_python_interpreter: /usr/bin/python3


- name: UPDATE CACHE
  hosts: all
  tasks:
    - name: UPDATE APT AND CACHE
      ansible.builtin.apt: update_cache=yes force_apt_get=yes
      register: update_result
    - debug: var=update_result


- name: INSTALL PACKAGES
  hosts: all
  tasks:
    - name: INSTALL DOCKER
      ansible.builtin.apt:
        pkg:
          - docker
          - docker-compose
        state: present
        update_cache: true
        force_apt_get: true
      register: install_result

    - name: START DOCKER DAEMON
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: true

- name: COPY FILES
  hosts: all
  tasks:
    - name: COPY JENKINS DOCKER-COMPOSE FILE TO CI SERVER
      ansible.builtin.copy:
        src: ../docker-compose.yaml
        dest: /root/docker-compose.yaml
        mode: +x

    - name: START CONTAINERS FROM COMPOSE
      community.docker.docker_compose:
        project_src: /root

- name: CONFIGURE JENKINS
  hosts: all
  tasks:
    - name: GIVE DOCKER SOCKET PERMISSION TO JENKINS USER
      community.docker.docker_container_exec:
        container: jenkins
        user: root
        command: /bin/bash -c "chmod 666 /var/run/docker.sock"
    - name: CREATE SSH DIR INSIDE JENKINS CONTAINER
      community.docker.docker_container_exec:
        container: jenkins
        user: jenkins
        command: /bin/bash -c "mkdir /var/jenkins_home/.ssh"   # we are using jenkins_home dir here because it is mounted as volume and this is the home directory for jenkins user inside jenkins container
    - name: GENERATE SSH KEY INSIDE JENKINS CONTAINER
      community.docker.docker_container_exec:
        container: jenkins
        user: jenkins
        command: /bin/sh -c "ssh-keygen -t rsa -b 4096 -C 'jenkins@jenkins' -f /var/jenkins_home/.ssh/id_rsa -N ''"
