def Build(){
    sh "mvn clean package" // this will clean all the files that were previously generated by maven
}

def Test(){
    echo "Testing the application..."
}

def Deploy(){
    // echo "deploying the application"
    // sh 'docker run -d -p 8081:8080 ankitraz/maven-app:latest'
    def dockerCmd = 'docker run -d -p 8081:8080 ankitraz/maven-app:latest'
    sshagent(['ec2-server-key']){
        sh "ssh -o StrictHostkeyChecking=no ${EC2_USER}@${EC2_HOST} ${dockerCmd}"
    }
}

return this